### ISSUE TITLE
use spaCy for NLP

### ISSUE THREAD

**Issue by deanmalmgren** [LeapBeyond/scrubadub#18] opened 2016-02-29 10:35 UTC
Looks like it does some pretty nice named entity recognition, which would probably be quite a bit better than textblob's PoS tagging. 

https://spacy.io/

**Comment by nahrwl** [comment] 2017-11-24 08:30
I gave implementing this a try. Searching for PERSON entities seems to be hit or miss, spaCy seems to think Dean Malmgren is an organization instead of a person. Also, it doesn't really work if the name isn't capitalized.

Broadening the search to all entities or some entities meant the Name detector would often overlap with other detectors, which might be fine?

https://github.com/nahrwl/scrubadub/tree/spacy-name-detector
(note that you need to run `python -m spacy download en` after running the pip install.)

**Comment by deanmalmgren** [comment] 2017-11-24 11:58
Thanks for taking a crack at this @nahrwl! Misclassifying names as organizations instead of people seems like an OK problem, provided it does a good job of omitting the information to begin with. I wonder if spaCy has higher recall than our first pass POS tagging approach...

I'm pretty sure that improving precision (e.g. correctly differentiating between people and organization names) will require some fairly adept machine learning models. I'm not entirely sure how spaCy's entity recognition works, but I seem to recall that they were using some statistical models to detect different types of entities. Did you have a chance to dig into this at all?

**Comment by aCampello** [comment] 2019-08-30 12:54
A bit late on the discussion, I also had a crack at using Spacy on top of the your original TextBlob detector for a project I ran last summer. To be fair, most of the entities have been captured by your name detector, although I do not have the precise numbers here. Their latest model promises 85% recall on average over all classes,  but it does not describe the stats per class (pending an open discussion on their gitter).

The approach that worked better for was to use Spacy **on top of** your POS approach, and take a very conservative decision: if any of the two classifies it as name, then replace it.

The advantage of Spacy, though, is that it unblocks a whole new possibilities of named entities. For instance, you can chose to replace geographic locations, addresses (GPE, LOC).

After spacy, there are some pretty involved machine learning for other [types of NER](https://medium.com/@b.terryjack/nlp-pretrained-named-entity-recognition-7caa5cd28d7b), but since those are statistical I don't know if you guys want to go down that route. I am keen to help with any of the above, if that's the case.

**Comment by deanmalmgren** [comment] 2019-08-30 14:14
Thanks for sharing these reflections @aCampello . Very interesting. I was keen on going down the ML route but I haven't been proactively supporting this package for quite a while with a day job that overfloweth. Please feel free to contribute a PR to that effect; would be awesome to incorporate both your expertise with spacy as well as addressing other, more nuanced, sensitive information that need to be removed.

I definitely agree that a more conservative approach is the way to go on this. 🙌

**Comment by alext234** [comment] 2019-09-20 03:47
+1 keen to know if spacy will really help in this case.

**Comment by thomasbird** [comment] 2020-10-16 15:29
For who ever picks this up, there is a new version of spacy (v3): https://explosion.ai/blog/spacy-v3-nightly

v2 didn't have a very good NER model, but v3 integrates some great NER models. We should integrate v3 of spacy.

**Comment by aCampello** [comment] 2020-10-17 17:59
I'd like to work on this issue. Having had an initial look into the nightly it looks like the NER will improve significantly over `TextBlob`, currently used by scrubadub. There are a couple of difficulties to incorporating this, though. Here are some thoughts - would be good to know what you think before open a [WIP] PR @thomasbird:

My thought was to:

-  Add a parameter `backend` to the initialisation of `detectors.name.NameDetector` that can take values `textblob` and `spacy`. The spacy backend will then use the transformers based pipeline (https://nightly.spacy.io/models/en#en_core_web_trf)
- Move the `textblob` logic inside `iter_flith` to a private method that can switch between `textblob` and `spacy`
- (?) In the spirit of backwards compatibility, we can leave textblob as default for now?

Here are two problems: 

1. We need to load the spacy model before processing (usually doing something like `nlp = spacy.load('en_core_web_trf')`), which cannot be done at runtime because it takes very long. My proposal is to add some logic to `scrubbers.Scrubber.__init__` to check whether we have spacy as backend and, if we do, to initialise it upon initialisation of the class.

2. From my experience, Spacy is *way* more efficient if you apply it into batches of documents (e.g. https://nightly.spacy.io/usage/processing-pipelines#processing). The problem is that the scrubber iterates one document at a time, regardless of which detector. We need again to add some logic to `scrubbers.Scrubber.clean_documents` to somehow send all documents to the Name detector at once.  This will probably need to change significantly the following lines:

https://github.com/LeapBeyond/scrubadub/blob/c7452882be2c52a6caf04c696b8018d7a1c50169/scrubadub/scrubbers.py#L164-L175

Perhaps we can use the `.iter_filth_documents` to understand which Detectors need batches of documents, and which ones can be done iteratively. Another idea is to add another detector property (say `batch_detector`) to `detector_configuration`). 

Would be good to get your thoughts on those!

**Comment by thomasbird** [comment] 2020-10-19 09:57
Sounds great!

My proposal would be that we have a new spacy detector rather than building upon the existing name detector. The reason being the same detector could also use spacys NER tagging to tag other things such as: ORG, LOG, GPE, NORP, FAC, ... (https://spacy.io/api/annotation#named-entities). 

1. Great plan.
2. I think I have a mild preference for just detecting if the `iter_filth_documents` function is defined rather than extra configuration. But, just my two cents.

Looking forward to it! Thanks!

**Comment by aCampello** [comment] 2020-10-20 09:52
Ok, cool, I will start working on that in my fork, with another branch on top of the new api branch. Hopefully there won't be many conflicts.

On a different note, my request for accuracy per label has been accepted and merged to spacy (probably will be available in the next release), so we will be able to say something about accuracy in removing names: https://github.com/explosion/spaCy/issues/6266

**Comment by aCampello** [comment] 2020-10-22 22:29
Started with this reporting on a branch in my fork:

https://github.com/LeapBeyond/scrubadub/compare/master...aCampello:feature/spacy_detector?expand=1

**Comment by aCampello** [comment] 2020-11-05 22:37
Can we close this, given https://github.com/LeapBeyond/scrubadub/pull/64?

**Comment by thomasbird** [comment] 2020-11-06 12:54
Yes sounds great, thanks again for working on this!

**Closed by thomasbird** 2020-11-06 12:54 UTC
Labels: feature request
