### ISSUE TITLE
update deprecated package sklearn to scikit-learn

### ISSUE THREAD

**Issue by sadams-evi** [LeapBeyond/scrubadub#148] opened 2023-08-01 15:47 UTC
- The 'sklearn' PyPI package is deprecated, use 'scikit-learn in scrubadub' 
- The deprecated packages causes error when using with python >3.8

**Comment by thomasbird** [comment] 2023-09-01 14:51
Thanks for reporting this, it seems to be a duplicate of #142 (which is being resolved now), so I'm closing this ticket.

**Closed by thomasbird** 2023-09-01 14:51 UTC
