### ISSUE TITLE
The 'sklearn' PyPI package is deprecated, use 'scikit-learn'

### ISSUE THREAD

**Issue by theconor** [LeapBeyond/scrubadub#142] opened 2022-12-18 15:18 UTC
Hi, I got the following error when trying` pip install scrubadub`:

error: subprocess-exited-with-error
  

>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [18 lines of output]
>       The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
>       rather than 'sklearn' for pip commands.
>       
>       Here is how to fix this error in the main use cases:
>       - use 'pip install scikit-learn' rather than 'pip install sklearn'
>       - replace 'sklearn' by 'scikit-learn' in your pip requirements files
>         (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
>       - if the 'sklearn' package is used by one of your dependencies,
>         it would be great if you take some time to track which package uses
>         'sklearn' instead of 'scikit-learn' and report it to their issue tracker
>       - as a last resort, set the environment variable
>         SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
>       
>       More information is available at
>       https://github.com/scikit-learn/sklearn-pypi-package
> 

According to the link above, this happened because I tried the install at 0 to 5 minutes past the hour during the month of December.  It worked OK 5 minutes later, but with the warning that the first package was deprecated.   Thanks for your help.

**Comment by mabreuortega** [comment] 2023-06-21 19:12
The issue is not fixed yet, code was merged but pipelines were cancelled

**Comment by thomasbird** [comment] 2023-09-01 14:53
This has been addressed in v2.0.1, which should be released in a few moments. Thanks for reporting this!

**Closed by thomasbird** 2023-09-01 14:53 UTC
